//! Names referencing items in the mongodb/mongo etc/evergreen.yml.

// Functions to setup tasks
/// Function setup authentication to evergreen API.
pub const CONFIGURE_EVG_API_CREDS: &str = "configure evergreen api credentials";
/// Function to setup a resmoke task.
pub const DO_SETUP: &str = "do setup";

// Functions for running fuzzers.
/// Function to setup fuzzer.
pub const SETUP_JSTESTFUZZ: &str = "setup jstestfuzz";
/// Function to generated fuzzer tests.
pub const RUN_FUZZER: &str = "run jstestfuzz";
/// Function to run tests generated by fuzzer.
pub const RUN_GENERATED_TESTS: &str = "run generated tests";

// Function for multi-version tests.
/// Function to do setup for multi-version testing.
pub const DO_MULTIVERSION_SETUP: &str = "do multiversion setup";
/// Function to get the project with no modules.
pub const GET_PROJECT_WITH_NO_MODULES: &str = "git get project no modules";
/// Function to add a git tag.
pub const ADD_GIT_TAG: &str = "add git tag";

// Functions for generating tasks.
pub const GENERATE_RESMOKE_TASKS: &str = "generate resmoke tasks";

// Tasks
/// Task which creates artifacts needed to execute tests.
pub const ARTIFACT_CREATION_TASK: &str = "archive_dist_test_debug";

// Vars
/// Variable that indicates a task is a fuzzer.
pub const IS_FUZZER: &str = "is_jstestfuzz";
